---
# Settings here are the default settings for all hosts.
# They can be overridden in the host.yml file.
# Vagrant (VirtualBox) will use these settings by default.
#
hostname: "Wikijs" # your hostname

# The developer user is a privileged user with shell and sudo access.
developer: "dev" # I like short names for typing ;)

### Project specific settings These should be overridden in the host.yml file ###
PROJECT_ACCOUNT: "wiki" # The account name of the project
PROJECT_DOMAIN: "wiki.example" # The domain name of the project
apache_vhosts:
  - servername: "{{PROJECT_DOMAIN}}"
    extra_parameters: |
      ProxyPreserveHost Off
      ProxyPass / http://0.0.0.0:3000/
      ProxyPassReverse / http://0.0.0.0:3000/

apache_mods_enabled:
  - proxy_http.load
  - proxy.load
  - headers.load

### Modify these defaults if you need to and are aware of the consequences ###

container_name: portainer
container_image: portainer/portainer-ce
container_ports: 9000:9000

# =====================  Auto generated do not modify. ===================== #

developer_group: "{{developer}}"
developer_path: "/home/{{developer}}"

docker_users:
  - "{{ PROJECT_ACCOUNT }}"
  - "{{ developer }}"
