---
# For machines without a domain name
# you can use it's public IP address
ansible_host: wiki.mydomain.com # dev machine
# This is the default user on an ubuntu install.
ansible_ssh_user: wiki
# The path on the control node where the
# ssh private key is stored.
# The default value is common
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
hostname: "mydomain.com" # your hostname
tz: "America/New_York" # the timezone of your server
PROJECT_DOMAIN: "wiki.mydomain.com" # The domain name of the project

#  These are defaults for most machines
ansible_connection: ssh
ansible_python_interpreter: /usr/bin/python3
